/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vistas;

import java.awt.EventQueue;
import javax.swing.UIManager;

/**
 *
 * @author Iann
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setExtendedState(FrmMenu.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reserva de habitaciones y Gestion de ventas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        lblidPersona = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        lblId2 = new javax.swing.JLabel();
        lblId3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mSistema = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        mInventario = new javax.swing.JMenu();
        mnProductos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnReservas = new javax.swing.JMenuItem();
        mnHabitaciones = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenuItem();
        mConfiguracion = new javax.swing.JMenu();
        mnUsuarios = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mnAcercaDe = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 153, 153));

        lblidPersona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblidPersona.setForeground(new java.awt.Color(255, 255, 255));
        escritorio.add(lblidPersona);
        lblidPersona.setBounds(90, 60, 90, 20);

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje.setText("Bienvenido al sistema : ");
        escritorio.add(lblMensaje);
        lblMensaje.setBounds(10, 10, 220, 25);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        escritorio.add(lblNombre);
        lblNombre.setBounds(90, 80, 160, 20);

        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        escritorio.add(lblApellido);
        lblApellido.setBounds(90, 100, 160, 20);

        lblAcceso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAcceso.setForeground(new java.awt.Color(255, 255, 255));
        escritorio.add(lblAcceso);
        lblAcceso.setBounds(90, 120, 170, 20);

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Cargo:");
        escritorio.add(lblId);
        lblId.setBounds(10, 120, 90, 20);

        lblId1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId1.setForeground(new java.awt.Color(255, 255, 255));
        lblId1.setText("ID:");
        escritorio.add(lblId1);
        lblId1.setBounds(10, 60, 90, 20);

        lblId2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId2.setForeground(new java.awt.Color(255, 255, 255));
        lblId2.setText("Nombres:");
        escritorio.add(lblId2);
        lblId2.setBounds(10, 80, 90, 20);

        lblId3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId3.setForeground(new java.awt.Color(255, 255, 255));
        lblId3.setText("Apellidos:");
        escritorio.add(lblId3);
        lblId3.setBounds(10, 100, 90, 20);

        mSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/sistema.png"))); // NOI18N
        mSistema.setMnemonic('f');
        mSistema.setText("Sistema");

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/exit.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mSistema.add(exitMenuItem);

        menuBar.add(mSistema);

        mInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/inventario.png"))); // NOI18N
        mInventario.setMnemonic('e');
        mInventario.setText("Inventario");

        mnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/products.png"))); // NOI18N
        mnProductos.setMnemonic('y');
        mnProductos.setText("Productos");
        mnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProductosActionPerformed(evt);
            }
        });
        mInventario.add(mnProductos);

        menuBar.add(mInventario);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/reserva.png"))); // NOI18N
        jMenu1.setText("Reservas");

        mnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/reservaaaa.png"))); // NOI18N
        mnReservas.setText("Reservas");
        mnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReservasActionPerformed(evt);
            }
        });
        jMenu1.add(mnReservas);

        mnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/rooms.png"))); // NOI18N
        mnHabitaciones.setMnemonic('t');
        mnHabitaciones.setText("Habitaciones");
        mnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHabitacionesActionPerformed(evt);
            }
        });
        jMenu1.add(mnHabitaciones);

        mnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clients.png"))); // NOI18N
        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnClientes);

        menuBar.add(jMenu1);

        mConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/settings.png"))); // NOI18N
        mConfiguracion.setText("Configuración");

        mnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clients.png"))); // NOI18N
        mnUsuarios.setText("Usuarios y accesos");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        mConfiguracion.add(mnUsuarios);

        menuBar.add(mConfiguracion);

        mAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/help.png"))); // NOI18N
        mAyuda.setText("Ayuda");

        mnAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/incog.png"))); // NOI18N
        mnAcercaDe.setText("Acerca de");
        mnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAcercaDeActionPerformed(evt);
            }
        });
        mAyuda.add(mnAcercaDe);

        menuBar.add(mAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHabitacionesActionPerformed
        FrmHabitacion form = new FrmHabitacion();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnHabitacionesActionPerformed

    private void mnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProductosActionPerformed
        FrmProductos form = new FrmProductos();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnProductosActionPerformed

    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        FrmCliente form = new FrmCliente();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        FrmTrabajador form = new FrmTrabajador();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnUsuariosActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReservasActionPerformed
        FrmReserva form = new FrmReserva();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        FrmReserva.txtIdTrabajador.setText(lblidPersona.getText());
        FrmReserva.txtTrabajador.setText(lblNombre.getText() + " " + lblApellido.getText());
        FrmReserva.idusuario = Integer.parseInt(lblidPersona.getText());
    }//GEN-LAST:event_mnReservasActionPerformed

    private void mnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAcercaDeActionPerformed
        FrmAcercaDe form = new FrmAcercaDe();
        escritorio.add(form);
        form.toFront();        
        form.setVisible(true);
    }//GEN-LAST:event_mnAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Throwable e) {
                    e.printStackTrace();
                }
                EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        try {
                            FrmMenu frame = new FrmMenu();
                            frame.setVisible(true);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    public static javax.swing.JLabel lblAcceso;
    public static javax.swing.JLabel lblApellido;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JLabel lblId1;
    public static javax.swing.JLabel lblId2;
    public static javax.swing.JLabel lblId3;
    private javax.swing.JLabel lblMensaje;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JLabel lblidPersona;
    private javax.swing.JMenu mAyuda;
    public static javax.swing.JMenu mConfiguracion;
    public static javax.swing.JMenu mInventario;
    private javax.swing.JMenu mSistema;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnAcercaDe;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnHabitaciones;
    private javax.swing.JMenuItem mnProductos;
    private javax.swing.JMenuItem mnReservas;
    private javax.swing.JMenuItem mnUsuarios;
    // End of variables declaration//GEN-END:variables

}
